// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// testrcpp
arma::mat testrcpp(arma::mat XX);
RcppExport SEXP _RChoiceHB_testrcpp(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(testrcpp(XX));
    return rcpp_result_gen;
END_RCPP
}
// RChoiceHB
Rcpp::List RChoiceHB(int nRespondents, int nPar, Rcpp::IntegerVector featureLengths, arma::mat X_cat, arma::uvec Y_indexed, arma::uvec yIndices_old, int numberOfScreens, int packagesPerScreen);
RcppExport SEXP _RChoiceHB_RChoiceHB(SEXP nRespondentsSEXP, SEXP nParSEXP, SEXP featureLengthsSEXP, SEXP X_catSEXP, SEXP Y_indexedSEXP, SEXP yIndices_oldSEXP, SEXP numberOfScreensSEXP, SEXP packagesPerScreenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nRespondents(nRespondentsSEXP);
    Rcpp::traits::input_parameter< int >::type nPar(nParSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type featureLengths(featureLengthsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_cat(X_catSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Y_indexed(Y_indexedSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type yIndices_old(yIndices_oldSEXP);
    Rcpp::traits::input_parameter< int >::type numberOfScreens(numberOfScreensSEXP);
    Rcpp::traits::input_parameter< int >::type packagesPerScreen(packagesPerScreenSEXP);
    rcpp_result_gen = Rcpp::wrap(RChoiceHB(nRespondents, nPar, featureLengths, X_cat, Y_indexed, yIndices_old, numberOfScreens, packagesPerScreen));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RChoiceHB_testrcpp", (DL_FUNC) &_RChoiceHB_testrcpp, 1},
    {"_RChoiceHB_RChoiceHB", (DL_FUNC) &_RChoiceHB_RChoiceHB, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_RChoiceHB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
