# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testrcpp <- function(XX) {
    .Call('_RChoiceHB_testrcpp', PACKAGE = 'RChoiceHB', XX)
}

RChoiceHB <- function(nRespondents, nPar, featureLengths, X_cat, Y_indexed, yIndices_old, numberOfScreens, packagesPerScreen) {
    .Call('_RChoiceHB_RChoiceHB', PACKAGE = 'RChoiceHB', nRespondents, nPar, featureLengths, X_cat, Y_indexed, yIndices_old, numberOfScreens, packagesPerScreen)
}

